name: CI Pipeline

on:
  push:
    branches:
      - main # Change to your main branch name if diff
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push user-service Image
        run: |
          docker build -t $DOCKER_USERNAME/user-service:latest -f ./backend/user-service/Dockerfile ./backend/user-service
          docker push $DOCKER_USERNAME/user-service:latest

      - name: Build and Push product-service Image
        run: |
          docker build -t $DOCKER_USERNAME/product-service:latest -f ./backend/product-service/Dockerfile ./backend/product-service
          docker push $DOCKER_USERNAME/product-service:latest

      - name: Build and Push order-service Image
        run: |
          docker build -t $DOCKER_USERNAME/order-service:latest -f ./backend/order-service/Dockerfile ./backend/order-service
          docker push $DOCKER_USERNAME/order-service:latest

      - name: Build and Push api-gateway Image
        run: |
          docker build -t $DOCKER_USERNAME/api-gateway:latest -f ./backend/api-gateway/Dockerfile ./backend/api-gateway
          docker push $DOCKER_USERNAME/api-gateway:latest

      - name: Build and Push client Image
        run: |
          docker build -t $DOCKER_USERNAME/client:latest ./client 
          docker push $DOCKER_USERNAME/client:latest

      - name: Log out from Docker Hub
        run: docker logout
